# Configuration example
PSI_THRESHOLD = 0.1			# PSI threshold
RECLAIM_RATIO = 0.1			# Reclaim ratio, between 0 and 1
RECLAIM_ACCURACY = 0.6			# Reclaim accuracy ratio, between 0 and 1
SCAN_EFFICIENCY = 0.1			# Reclaim scan efficiency ratio, between 0 and 1
MIN_SIZE = 1G				# 1G Minimum memory limit, in bytes
RECLAIM_SIZE = 420M			# Totle reclaim size
ITERATE_MAX_SIZE = 3M			# 2M Single iterate maximum memory limit, in bytes
ITERATE_MIN_SIZE = 1M			# 1M Single iterate minmum memory limit, in bytes
INTERVAL = 20				# Sampling interval, seconds
